version: 2
executorType: docker
containerInfo:
  - image: ubuntu:16.04
stages:
  build:
    parallel: 4
    steps:
      - type: setup-docker-engine
      - type: shell
        command: docker build --rm=false -f Dockerfile-ubuntu --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t "reynn/ansible:$ANSIBLE_VERSION-ubuntu" .
      - type: shell
        command: docker build --rm=false -f Dockerfile-alpine --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t "reynn/ansible:$ANSIBLE_VERSION-alpine" .
      - type: shell
        command: docker build --rm=false -f Dockerfile-centos --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t "reynn/ansible:$ANSIBLE_VERSION-centos" .
      - type: shell
        command: docker build --rm=false -f Dockerfile-fedora25 --build-arg ANSIBLE_VERSION=$ANSIBLE_VERSION -t "reynn/ansible:$ANSIBLE_VERSION-fedora25" .

  # test:
    # parallel: 4
    # steps:
      - type: shell
        command: docker run --rm -it "reynn/ansible:$ANSIBLE_VERSION-ubuntu" --version
      - type: shell
        command: docker run --rm -it "reynn/ansible:$ANSIBLE_VERSION-alpine" --version
      - type: shell
        command: docker run --rm -it "reynn/ansible:$ANSIBLE_VERSION-centos" --version
      - type: shell
        command: docker run --rm -it "reynn/ansible:$ANSIBLE_VERSION-fedora25" --version

  # deployment:
    # steps:
      - type: deploy
        shell: /bin/sh
        command: docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      # - type: deploy
      #   shell: /bin/sh
      #   command: docker push "reynn/ansible:$ANSIBLE_VERSION-ubuntu"
      # - type: deploy
      #   shell: /bin/sh
      #   command: docker push "reynn/ansible:$ANSIBLE_VERSION-alpine"
      # - type: deploy
      #   shell: /bin/sh
      #   command: docker push "reynn/ansible:$ANSIBLE_VERSION-centos"
      # - type: deploy
      #   shell: /bin/sh
      #   command: docker push "reynn/ansible:$ANSIBLE_VERSION-fedora25"
