FROM alpine:3.5

WORKDIR /ansible

ENV ANSIBLE_VERSION 2.3.0.0

LABEL ANSIBLE_VERSION=$ANSIBLE_VERSION \
      ALPINE_VERSION=3.5

RUN apk add --update --no-cache \
        python \
        py-pip \
        libffi \
        openssl-dev \
    && apk add --update --no-cache --virtual build-deps \
        python-dev \
        build-base \
        libffi-dev \
    && pip install --upgrade pip ansible==${ANSIBLE_VERSION} \
    && apk del build-deps

ENTRYPOINT [ "ansible" ]
