FROM ubuntu:16.04

WORKDIR /ansible

ARG ANSIBLE_VERSION

RUN apt update \
    && apt install -y \
        python \
        python-pip \
        libffi-dev \
        libssl-dev \
        python-dev \
    && pip install --upgrade pip ansible==${ANSIBLE_VERSION}

ENTRYPOINT [ "ansible" ]
