FROM centos:7

WORKDIR /ansible

ENV ANSIBLE_VERSION 2.3.0.0

RUN yum install -y epel-release \
    && yum install -y \
        python \
        python-pip \
        python-devel \
        gcc \
        libffi-devel \
        openssl-devel \
    && pip install -U pip  ansible==${ANSIBLE_VERSION}

ENTRYPOINT [ "ansible" ]
