FROM ubuntu:17.04

WORKDIR /ansible

ENV ANSIBLE_VERSION 2.3.0.0

RUN apt update \
    && apt install -y \
        python \
        python-pip \
        libffi-dev \
        libssl-dev \
        python-dev \
    && pip install --upgrade pip ansible==${ANSIBLE_VERSION}

ENTRYPOINT [ "ansible" ]
